# Operating System
import os

# Set password
pas=input("Set password:")
os.system('cls' if os.name == 'nt' else 'clear')

# Main-Menu
def mainmenu():
    print("\n\n\n|-------------------------|")
    print("|         ~Notemp~        |License: GPLv3")
    print("|-private temporary notes-|Project created by: https://github.com/untitled-guy ")
    print("|-------------------------|")
    ewp=input("Password:")
    if ewp == pas:
        # Take notes
        os.system('cls' if os.name == 'nt' else 'clear')
        print("Notes:                -(30 lines)-")
        n1=input("1.")
        n2=input("2.")
        n3=input("3.")
        n4=input("4.")
        n5=input("5.")
        n6=input("6.")
        n7=input("7.")
        n8=input("8.")
        n9=input("9.")
        n0=input("10.")
        n11=input("11.")
        n22=input("12.")
        n33=input("13.")
        n44=input("14.")
        n55=input("15.")
        n66=input("16.")
        n77=input("17.")
        n88=input("18.")
        n99=input("19.")
        n00=input("20.")
        n111=input("21.")
        n222=input("22.")
        n333=input("23.")
        n444=input("24.")
        n555=input("25.")
        n600=input("26.")
        n777=input("27.")
        n888=input("28.")
        n999=input("29.")
        n000=input("30.")
        def notes():
            print(n1)
            print(n2)
            print(n3)
            print(n4)
            print(n5)
            print(n6)
            print(n7)
            print(n8)
            print(n9)
            print(n0)
            print(n11)
            print(n22)
            print(n33)
            print(n44)
            print(n55)
            print(n66)
            print(n77)
            print(n88)
            print(n99)
            print(n00)
            print(n111)
            print(n222)
            print(n333)
            print(n444)
            print(n555)
            print(n600)
            print(n777)
            print(n888)
            print(n999)
            print(n000)
        def menu():
            # menu
            os.system('cls' if os.name == 'nt' else 'clear')
            ewp=input("Password:")
            if ewp == pas:
                print("(1)See notes")
                print("(2)Lock")
                print("(3)Write")
                print("(/)exit")
                fg=input("\n==>")
                if fg == "1":
                    notes()
                    input("press enter to lock: ")
                    os.system('cls' if os.name == 'nt' else 'clear')
                    menu()
                if fg == "2":
                    os.system('cls' if os.name == 'nt' else 'clear')
                    menu()
                if fg == "3":
                    os.system('cls' if os.name == 'nt' else 'clear')
                    mainmenu()
        menu()
        # wrong password
    if ewp != pas:
        print("wrong password")
        input("press enter to exit: ")
mainmenu()